steps:
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        DOCKER_BUILDKIT=1 docker build -t gcr.io/$PROJECT_ID/minecraft-server .
images:
  - 'gcr.io/$PROJECT_ID/minecraft-server'
